# This file generates the GitHub Actions matrix
---
include:

  # sweep
  - board: nice_nano_v2
    shield: central_dongle dongle_display
    artifact-name: central_dongle
  - board: nice_nano_v2
    shield: lily58_left
  - board: nice_nano_v2
    shield: lily58_right

  # reset
  - board: nice_nano_v2
    shield: settings_reset
