# This file generates the GitHub Actions matrix
---
include:
    # cradio
  - board: nice_nano_v2
    shield: cradio_left
    artifact-name: sweep_left
  - board: nice_nano_v2
    shield: cradio_right
    artifact-name: sweep_right

  - board: nice_nano_v2
    shield: cradio_left
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
    artifact-name: sweep_left_with_logging

    # rommana
  - board: seeeduino_xiao_ble
    shield: rommana_left
    artifact-name: rommana_left
  - board: seeeduino_xiao_ble
    shield: rommana_right
    artifact-name: rommana_right
    
  - board: seeeduino_xiao_ble
    shield: rommana_left
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
    artifact-name: rommana_left_with_logging

    # sweep
  - board: seeeduino_xiao_ble
    shield: sweep_dongle dongle_display
    artifact-name: sweep_dongle
  - board: nice_nano_v2
    shield: sweep_left_central
    artifact-name: sweep_left_central
  - board: nice_nano_v2
    shield: sweep_left_peripheral
    artifact-name: sweep_left_peripheral
  - board: nice_nano_v2
    shield: sweep_right_peripheral
    artifact-name: sweep_right_peripheral
    
  - board: seeeduino_xiao_ble
    shield: sweep_dongle dongle_display
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
    artifact-name: sweep_dongle_with_logging

    # reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset