# This file generates the GitHub Actions matrix
---
include:

  # sweep dongle
  - board: nrf52840
    shield: sweep_central_dongle dongle_display
    artifact-name: sweep_central_dongle
  #lily58
  - board: nice_nano_v2
    shield: lily58_left
  - board: nice_nano_v2
    shield: lily58_right

  # reset
  - board: nice_nano_v2
    shield: settings_reset
